### ISSUE TITLE
Is there a reason to run a cm-grasshopper binary with privileges?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cm-grasshopper#6]
cm-grasshopper 실행시 슈퍼유저 권한이 필요한 것으로 안내가 되어 있습니다. 혹시 특별한 이유가 있을까요?

https://github.com/cloud-barista/cm-grasshopper/blob/116589df2b99c33f57803e11218325bd1a2415b3/README.md?plain=1#L52-L55

특별한 사유가 있다면 make run 부분도 수정이 필요하지 않을까 싶습니다.

https://github.com/cloud-barista/cm-grasshopper/blob/116589df2b99c33f57803e11218325bd1a2415b3/README.md?plain=1#L82-L89

**Comment by ish-hcc** [comment]
@sykim-etri 기존에 프로토타입을 구현하여 테스트 하면서 root 체크 코드가 남아있는것으로 확인되었습니다. 현재는 root 권한이 필요하지 않아 실행중인 사용자 권한으로 작동할 수 있도록 수정하였습니다.
